general:
  data_dir: data
  log_level: DEBUG
retry:
  backoff_factor: 2.0
  base_delay: 1.0
  jitter: true
  jitter_factor: 0.25
  max_delay: 60.0
  max_retries: 3
tier1:
  enabled: false
  default_model: llama3
tier2:
  enabled: false
  ollama:
    base_url: http://localhost:11434
    cache_dir: null
    cache_enabled: false
    cache_ttl: 86400
    complex_model: deepseek-r1:latest 
    default_model: deepseek-r1:latest  # Use the correct model name with version
    log_interval: 100
    max_cache_entries: 1000
    max_cache_size_mb: 100
    max_tokens: 500
    temperature: 0.7
tier3:
  bedrock:
    default_model: amazon.nova-micro-v1:0
    max_tokens: 1000
    models:
      # complex: amazon.titan-text-express-v1  # This line is commented out and won't be used
      default: amazon.nova-micro-v1:0
    region_name: us-east-1
    temperature: 0.7
    timeout: 30
  enabled: true
  prompt_optimizer:
    avg_chars_per_token: 4
    enabled: true
    max_prompt_tokens: 800
    system_prompts:
      high: You are a helpful bilingual dog companion in a Japanese train station.
        Your role is to assist the player with language help, directions, and cultural
        information. Provide detailed explanations when appropriate.
      low: You are a helpful bilingual dog companion in a Japanese train station.
        Provide simple language help.
      medium: You are a helpful bilingual dog companion in a Japanese train station.
        Assist with language help, directions, and basic cultural information.
  usage_tracker:
    auto_save: true
    cost_per_1k_input_tokens:
      amazon.nova-micro-v1:0: 0.0003
      amazon.titan-text-express-v1: 0.0008
      anthropic.claude-3-haiku-20240307-v1:0: 0.00025
      anthropic.claude-3-sonnet-20240229-v1:0: 0.003
      default: 0.001
    cost_per_1k_output_tokens:
      amazon.nova-micro-v1:0: 0.0006
      amazon.titan-text-express-v1: 0.0016
      anthropic.claude-3-haiku-20240307-v1:0: 0.00125
      anthropic.claude-3-sonnet-20240229-v1:0: 0.015
      default: 0.002
    daily_token_limit: 100000
    enabled: true
    hourly_request_limit: 100
    monthly_cost_limit: 50.0
    storage_path: data/usage/bedrock_usage.json
