[server]
port = 8081
address = "localhost"

[theme]
primaryColor = "#1E3A8A"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "calibri"

[browser]
gatherUsageStats = false
